version: '2.0'
services:
  db:
    image: mariadb:10.6
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass123  
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - /opt/seafile-mysql/db:/var/lib/mysql  
    networks:
      - seafile-net

  memcached:
    image: memcached:1.6.18
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net
          
  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    ports:
      - "8081:80"
#     - "443:443"  
    volumes:
      - /opt/seafile-data:/shared   
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=pass123  
      - TIME_ZONE=Asia/Jakarta  
      - SEAFILE_ADMIN_EMAIL=admin@email.com 
      - SEAFILE_ADMIN_PASSWORD=pass123    
      - SEAFILE_SERVER_LETSENCRYPT=false 
      # - SEAFILE_SERVER_HOSTNAME=hostname.com # optional if https is enabled.
    depends_on:
      - db
      - memcached
    networks:
      - seafile-net

networks:
  seafile-net: