version: '3.3'
services:
  postgre:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminganteng123
    ports:
      - '5432:5432'
    volumes:
      - db-postgre:/var/lib/postgresql/data
volumes:
  db-postgre:
    driver: local
