version: '3.3'
services:
  dbadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "developer@chakra.uno"
      PGADMIN_DEFAULT_PASSWORD: "developercrm"
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  pgadmin:
