version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - 'discovery.type=single-node'
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ['CMD', 'curl', '-s', '-f', 'http://localhost:9200/_cat/health']
      interval: 3s
      timeout: 3s
      retries: 10
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.2
    container_name: logstash
    ports:
      - '5044:5044'
      - '9600:9600'
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    container_name: kibana
    ports:
      - '5601:5601'
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-s', '-f', 'http://localhost:5601/api/status']
      interval: 3s
      timeout: 3s
      retries: 50
    networks:
      - elk

networks:
  elk:
    driver: bridge
