version: '3'

services:

  # kong-database:
  #   image: postgres:9.6
  #   container_name: kong-database
  #   ports:
  #     - 5431:5432
  #   environment:
  #     - POSTGRES_USER=kong
  #     - POSTGRES_DB=kong
  #     - POSTGRES_PASSWORD=kong
  #   volumes:
  #     - "db-data-kong-postgres:/var/lib/postgresql/data"

#  kong-migrations:
 #   image: kong
  #  environment:
   #   - KONG_DATABASE=kong
    #  - KONG_PG_HOST=10.173.1.38
     # - KONG_PG_USER=postx-dev
      #- KONG_PG_PASSWORD=INJE2X2LIVBUKXZSGAZDECQ= 
      #- KONG_CASSANDRA_CONTACT_POINTS=kong
    #command: kong migrations bootstrap
    #restart: on-failure
    # depends_on:
    #   - kong-database

  kong:
    image: kong
    container_name: kong
    environment:
      - LC_CTYPE=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - KONG_DATABASE=kong
      - KONG_PG_HOST=10.173.1.38
      - KONG_PG_USER=postx-dev
      - KONG_PG_PASSWORD=INJE2X2LIVBUKXZSGAZDECQ=
      - KONG_CASSANDRA_CONTACT_POINTS=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    restart: on-failure
    ports:
      - 8080:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    # links:
    #   - kong-database:kong-database
    #depends_on:
     # - kong-migrations

  konga:
    container_name: konga
    image: pantsel/konga
    restart: always
#    networks:
 #     - kong-net
    environment:
      DB_ADAPTER: postgres
      DB_HOST: 10.173.1.38   # [change-me] : IP address of your postgresql database, must be accessible from konga node
      DB_PORT: 5432         # [change-me] : postgresql port
      DB_USER: postx-dev     # [change-me] : postgresql username
      DB_PASSWORD: INJE2X2LIVBUKXZSGAZDECQ=     # [change-me] : postgresql password
      # any string will OK for token
      TOKEN_SECRET: iu7YDcPLiZkozQXzZ9kka3Ee1Vid5ZgQ
      DB_DATABASE: konga_db
      NODE_ENV: production
    ports:
      - "1337:1337"

  # konga:
  #   image: pantsel/konga
  #   ports:
  #     - 1337:1337
  #   links:
  #     - kong:kong
  #   container_name: konga
  #   environment:
  #     - NODE_ENV=production

# volumes:
#   db-data-kong-postgres:

networks:
    default:
        external:
            name: kong-net
