version: '3'
services:
  teleport:
    image: public.ecr.aws/gravitational/teleport-distroless:14.0.1
    container_name: teleport
    restart: always
    hostname: localhost
    volumes:
      - ./config:/etc/teleport
      - ./data:/var/lib/teleport
    ports:
      - "3025:3025"
      - "3080:3080"